name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

##############################################################

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:

  lints:
    name: "Lints"
    runs-on: ubuntu-latest

    steps:
      - uses: wyvox/action@v1
      - run: pnpm lint

  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - uses: wyvox/action@v1
      - run: pnpm test 


